### ISSUE TITLE
Missing prerequisites section in README

### ISSUE THREAD

**Issue by faustogut** [viniciussanchez/dataset-serialize#1]
SUGGESTION:
You can add (maybe to the prerequisites section), Delphi versions supported for this project.

P.D. This suggestion applies to all your other Pascal projects too ;-)

**Comment by viniciussanchez** [comment]
Thank you...
I will try to test in other versions and add

**Comment by faustogut** [comment]
Leaving aside my suggestion about versions, I really mean you forgot to mention (as you used to do in other projects), README prerequisites section.

I know, I know. In this case, it seems to be obvious, but anyway, for coherence, I miss something like this (before installation steps):

### Prerequisites
 * [**Boss**](https://github.com/HashLoad/boss) - Dependency Manager for Delphi

**Comment by viniciussanchez** [comment]
Perfect! I really forgot about this session... What do you think now? Thanks in advance...

**Comment by faustogut** [comment]
Now it is OK. Thanks.

Another silly detail I saw is:
Installation**":"** (colon symbol attached at the end)

Did you do on purpose? or maybe is a little typo?
NOTICE: I saw this issue in other projects of yours too. ;-)

Excuse me for the silliness of my comments in advance.

**Comment by viniciussanchez** [comment]
No... typing error
