### ISSUE TITLE
Problema ao utilizar DataSet-Serialize nos Delphi antigos

### ISSUE THREAD

**Issue by Kyuorhan** [viniciussanchez/dataset-serialize#100]
#### Eu estava tendo problema ao utilizar DataSet-Serialize no Delphi 7, implementei a biblioteca com boss normalmente.

Pra tira informações do DBGrid e jogar num TEdit ou TMemo por exemplo ele joga normalmente manipulação direto sem problema. mais quando eu quero joga pro DBGrid na tabela e ele não joga. usei variais conexões tabela temporária e n deu, e usei o mesmo código no delphi versão mais recente ele funciona normalmente.

é algum recurso ou configuração eu devo alterar pra q funcione no delphi 7 ??

**Comment by viniciussanchez** [comment]
Nunca utilizei ele com Delphi 7. Eu nem tenho o Delphi 7 para testar. Precisava debugar e ver o que está acontecendo....

**Comment by Kyuorhan** [comment]
Então ele não representa nenhuma erro ele passar direto normalmente só não sei o porque, fui debugando as classe da biblioteca e eu não terminei tudo, mais pelo período dos eventos quase são idênticos pra delphi antigo e o novo. Se não eu acho que vou ter que fazer um controller pelo visto, meio que não sei se é o por causa da IDE antiga se interfere a biblioteca. Ai tenhos essas duvidas meio que sou novo no delphi.
