### ISSUE TITLE
Whay does the JSON string start with [ and end with ]

### ISSUE THREAD

**Issue by JacoFourie** [viniciussanchez/dataset-serialize#111]
Hi.

Why does the JSON object start with [ and end with ] ?

It breaks the JSON parsers.

I I convert a result set from POSTGRESQL I will get a string like this.

[{"week_total" : 1.6719999999999999E+001}]

**Comment by viniciussanchez** [comment]
It depends on how you are exporting...
.ToJSONObject() will create a {}
.TOJSONArray() will create a []

**Comment by JacoFourie** [comment]
OK thank you. That solved this problem.
