### ISSUE TITLE
any reason for enforcing 0 field count before importing from JSON to DataSet?

### ISSUE THREAD

**Issue by Khorkhe** [viniciussanchez/dataset-serialize#143]
i have a complex filter that cannot be achieved via standard SQLite or Filter event.
For that, a separate Boolean FieldDef is added prior to loading from JSON.

However when doing so (and in accordance to the docs), the JSON fields are not created.
commenting out the line below, works.

```
//    if ((ADataSet.FieldDefs.Count = 0) and (ADataSet.FieldCount = 0)) then
      LoadFieldsFromJSON(ADataSet, AJSONObject);
```

Could this be, maybe an option in the config, e.g. AllowExistingFields, defaulted to False to protect unknowing users, and yet allow those who want to proceed anyway, to do so?

**Comment by viniciussanchez** [comment]
Yes, if you don't have fields created, it creates based on JSON
