### ISSUE TITLE
FormatCurrency ignorado no MySQL

### ISSUE THREAD

**Issue by gleikocarmelo** [viniciussanchez/dataset-serialize#145]
O FormatCurrency é ignorado para campos DOUBLE (12,4) no MySQL.
Dentro do Delphi o campo é identificado como TFieldType.ftSingle

**Comment by viniciussanchez** [comment]
O FormatCurrency não é utilizado para esses campos hoje...

![image](https://user-images.githubusercontent.com/16382981/165813724-b51293db-ea9f-442e-b823-1b50c21dd965.png)

Teria que criar um FormatFloat e passar a utilizar o mesmo

**Comment by viniciussanchez** [comment]
O recurso acabou de ser implementado
