### ISSUE TITLE
Nome dos campos

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/dataset-serialize#146]
Bom dia, não vi na documentação com parametro passo para mandar os nomes dos campos como estão na tabela.

ex:
"estados_id"  muda para "estadosId"

Grato

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/162447268-96e9de62-b97f-4f04-a890-519f33ee1dda.png)
