### ISSUE TITLE
Bug ToJSONArray

### ISSUE THREAD

**Issue by pacopalao** [viniciussanchez/dataset-serialize#147]
Hello,
if you have a dataset with only one field (idalbc) an for example 3 records the result for ToJSONArray is:

[
    "23920",
    "23921",
    "23922"
]
is wrong

while if you have two fields (idalbc,fecha) the result is correct
[
    {
        "idalbc": "23920",
        "fecha": "2022-04-07 18:26:04.000"
    },
    {
        "idalbc": "23921",
        "fecha": "2022-04-07 18:34:29.000"
    },
    {
        "idalbc": "23922",
        "fecha": "2022-04-11 17:05:04.000"
    }
]

**Comment by viniciussanchez** [comment]
It's not wrong!
Normally, when you have 1 field, it is desirable to export as you saw.
But, if you want to change, just change the parameter to "False"

![image](https://user-images.githubusercontent.com/16382981/164717323-2dd78aba-1a71-48ee-9580-46e73356a6c7.png)
