### ISSUE TITLE
Nome das colunas iguais.

### ISSUE THREAD

**Issue by JohnnyRei** [viniciussanchez/dataset-serialize#148]
Tem alguma forma de deixar o retorno do JSON com os nomes iguais das colunas do banco de dados?

**Comment by viniciussanchez** [comment]
Sim, está na documentação.
![image](https://user-images.githubusercontent.com/16382981/166673312-b0e9e9fc-97a8-4934-8957-92d9c9dae078.png)

**Comment by JohnnyRei** [comment]
![image](https://user-images.githubusercontent.com/87324124/166701505-27017d06-5476-410b-aa1d-7f1b61e0f1a0.png)
![image](https://user-images.githubusercontent.com/87324124/166701632-6ddfe013-00d8-4241-be36-620993458d4f.png)

Tem que declarar alguma coisa antes?
