### ISSUE TITLE
Problemas com UUID

### ISSUE THREAD

**Issue by GusttavoSilva** [viniciussanchez/dataset-serialize#164]
Utilizo o banco de dados SQLServer e nele tem a função de utilizar o UUID como ID. porem quando eu envio um dataset direto como json ele envia esse ID entre chaves {}.

segue a imagem abaixo:
 
![image](https://user-images.githubusercontent.com/41659063/180282810-342367cc-38a1-4227-80d2-7275d2e9ed5e.png)

**Comment by viniciussanchez** [comment]
Boa tarde, conseguiu resolver o problema?

**Comment by GusttavoSilva** [comment]
Resolvi
