### ISSUE TITLE
Delphi XE7 - Android

### ISSUE THREAD

**Issue by alexguara78** [viniciussanchez/dataset-serialize#169]
boa tarde pessoal, não consigo compilar no Delphi Xe7 / android, dá o erro:
[DCC Fatal Error] DataSet.Serialize.pas(242): F2063 Could not compile used unit 'DataSet.Serialize.Import.pas'

poderiam me ajudar? obrigado

**Comment by viniciussanchez** [comment]
Bom dia, teria um print do erro? Em que linha da o erro? Esta com o projeto atualizado?

**Comment by viniciussanchez** [comment]
Boa tarde, conseguiu solucionar o problema?
