### ISSUE TITLE
Bug with fields with "_"

### ISSUE THREAD

**Issue by luapfr** [viniciussanchez/dataset-serialize#177]
can't return data when the field has "_" this example fails

[  {
    "id": 3,
    "des_ricao": "coca cola",
    "ativo": true,
    "prec_o": 2.50,
    "cadastro": "03/08/1995"
  }  ]

manages to mount the TFields but does not bring any data

**Comment by viniciussanchez** [comment]
this is not a bug, it's a configuration.  take a look at the documentation

**Comment by luapfr** [comment]
I didn't find anything in the documentation about "_" can you show me?

**Comment by ds-sampaio** [comment]
> Eu não encontrei nada na documentação sobre "_" você pode me mostrar?

Se vc configurar desse jeito vai consegui retornar
 TDataSetSerializeConfig.GetInstance.CaseNameDefinition := TCaseNameDefinition.cndLower;
