### ISSUE TITLE
Formatação de campos não aplicadas

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/dataset-serialize#191]
Tenho um banco de dados (FireBird 2.1, Dialect 1) com campos do tipo DATE e tento aplicar a formatação mas não funciona.

//configurações aplicadas
  TDataSetSerializeConfig.GetInstance.Export.FormatDate:= 'dd-mm-yyyy';
  TDataSetSerializeConfig.GetInstance.Export.FormatDateTime:= 'dd-mm-yyyy hh:nn:ss';

retornor:
{
   "cadastro":"2014-06-02T00:00:00.000Z",
}

**Comment by viniciussanchez** [comment]
![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/eb4191f1-1edf-4388-be5d-2580dabab6ae)
Se olhar a classe vai ver que esses dois parâmetros tem prioridade... verifica por favor como eles estão e tente novamente. Qualquer coisa coloca aqui para que possamos analisar por favor

**Comment by alissonrodrigo** [comment]
Minha classe está assim. Os únicos parâmetros que eu paço são estes dois de formatação.
![Screenshot_1](https://github.com/viniciussanchez/dataset-serialize/assets/8572209/ce63fcdc-38a5-489c-bbc0-9c4b2fedea47)

**Comment by alissonrodrigo** [comment]
Todo processo e criado em tempo de execução.

**Comment by alissonrodrigo** [comment]
a logica e esta:
procedure TdmClientes.Lancou_Clientes(aConexao: TFDConnection; dtLancou: TDateTime);
var
  Qry: TFDQuery;
  sPacote: string;
  jValores: TJSONArray;
begin
  
  TDataSetSerializeConfig.GetInstance.CaseNameDefinition := TCaseNameDefinition.cndLower;
  TDataSetSerializeConfig.GetInstance.Export.FormatDate:= 'dd-mm-yyyy';
  TDataSetSerializeConfig.GetInstance.Export.FormatDateTime:= 'dd-mm-yyyy hh:nn:ss';
  
	Qry := TFDQuery.Create(nil);
	try
      Qry.Active := False;
      Qry.Connection := aConexao;
      Qry.SQL.Clear;
      Qry.FetchOptions.Mode := TFDFetchMode.fmAll;
      Qry.SQL.Add('SELECT * FROM cliente');	  
	  jValores := Qry.ToJSONArray();
      sPacote := jValores.ToString;
      jValores.Free;
	finally    
      Qry.Free;
      Qry := nil;
    end;
	
end;

**Comment by alissonrodrigo** [comment]
Deu certo após adicionar essas condições
