### ISSUE TITLE
TDataSetSerializeAdapter not found

### ISSUE THREAD

**Issue by carlospo** [viniciussanchez/dataset-serialize#192]
Estou tentando usar as novas versões do RestRequest4D e DataSetSerialize, porem não consigo compilar com a nova alteração:
begin
  TRequest.New.BaseURL('http://localhost:8888/users')
    .Adapters(TDataSetSerializeAdapter.New(FDMemTable))
    .Accept('application/json')
    .Get;
end;
não encontro TDataSetSerializeAdapter.

**Comment by viniciussanchez** [comment]
Boa noite, na documentação do RESTRequest4Delphi está explicando...

![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/809784a7-f1e3-4a88-bd78-024a34bd8b08)

Ao clicar sobre o link, ele te direciona para este projeto aqui: https://github.com/viniciussanchez/dataset-serialize-adapter-restrequest4delphi

![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/a214d892-5b59-4e93-bb12-092eba8247bf)

Este por sua vez, é uma espécie de conector entre as duas bibliotecas. Isso foi feito para permitir que novos adapters / conectores sejam criados pelos usuários, e também para não deixar o RESTRequest4Delphi acoplado ao DataSet-Serialize. Visto que muitas pessoas usam o RESTRequest4Delphi, mas não usam a funcionalidade de carregar o JSON no DataSet, por exemplo....

**Comment by carlospo** [comment]
Boa noite, agradeço a resposta, mas o link esta “DataSet-Serialize” e eu já havia instalado, mas clicando no link foi para o pacote com nome correto dataset-serialize-adapter-restrequest4delphi, isso me confundio.

Abraço.


Sent from Mail for Windows

**Comment by viniciussanchez** [comment]
Entendi, a minha intenção lá era uma sessão para listar os Adapters criados...
E no caso é um Adapter para o DataSet-Serialize entendeu? Eu tinha pensado nessa ideia...
ai tipo, se for ter um outro adapter para o DataSetConverter4Delphi por exemplo, eu teria um link, com o nome DataSetConverter4Delphi apontando para o adapter da biblioteca em questão....
