### ISSUE TITLE
Cannot find type for field: type in question: ftOraClob

### ISSUE THREAD

**Issue by PedroPizzutti** [viniciussanchez/dataset-serialize#202]
![error](https://github.com/viniciussanchez/dataset-serialize/assets/87579876/bedd5e2b-fcc1-46dd-a998-f2db94e36921)

**Comment by viniciussanchez** [comment]
Boa tarde...
Eu aceitei seu PR, mas ainda preciso testar no Lazarus. Para ver se existe esse tipo lá... você chegou a ver?

**Comment by PedroPizzutti** [comment]
Boa noite!
Cheguei sim e o tipo existe por lá:
![lazarus_psK4e1wB7P](https://github.com/viniciussanchez/dataset-serialize/assets/87579876/13051ce1-7e7f-490b-90dc-76ab6bf3681f)

**Comment by viniciussanchez** [comment]
Legal... obrigado
