### ISSUE TITLE
Erro no lazarus

### ISSUE THREAD

**Issue by mbertolani** [viniciussanchez/dataset-serialize#205]
Vinicius,
segue duas modificações que precisei fazer pra funcionar o import no lazarus

funcao LoadFieldsFromJSON

linha 644
    LFieldDef.DataType := TDataSetSerializeUtils.GetDataType({$IF DEFINED(FPC)}AJSONObject.Items[I]{$ELSE}LJSONPair.JsonValue{$ENDIF});
    LFieldDef.Size := 0; // Adicionei essa linha porque estava dando erro dizendo que campos Integer, Float, Date tinham tamanho invalido com valor 20

funcao LoadBlobFieldFromStream

linha 608
    // TBlobField(AField).AsString := DecodeStringBase64(LStringStream.DataString);
    TBlobField(AField).LoadFromStream(LStringStream); // troquei a forma de carregar o valor porque estavam dando erro e ficando vazio

**Comment by viniciussanchez** [comment]
Oi, gostaria de enviar um pull request com o ajuste?

**Comment by mbertolani** [comment]
enviado

**Comment by viniciussanchez** [comment]
Obrigado

**Comment by mbertolani** [comment]
porque a versao do git esta diferente da versao baixada pelo Boss ?

**Comment by viniciussanchez** [comment]
@mbertolani Vou liberar uma nova versão hoje e ai ficará tudo igual.
