### ISSUE TITLE
SerializeAdapter 

### ISSUE THREAD

**Issue by cndcdf** [viniciussanchez/dataset-serialize#209]
Eu estou realizando um teste com o CodeTyphon,  no modo debug apresenta esse erro, alguém pode me ajudar?

![image](https://github.com/viniciussanchez/dataset-serialize/assets/378110/ca789c77-d029-44e9-866d-fc62d7188788)

**Comment by cndcdf** [comment]
o erro sumui quando desabilitei a opção Verify method calls, alguém sabe porque isso acontece e se eu posso deixar desmarcado?

![image](https://github.com/viniciussanchez/dataset-serialize/assets/378110/90bc5ad0-ead2-499b-9564-6f94ef09cdcb)

**Comment by viniciussanchez** [comment]
Desconheço...
