### ISSUE TITLE
Fragmentos do JSON

### ISSUE THREAD

**Issue by stonestecnologia** [viniciussanchez/dataset-serialize#210]
`{
  "success": true,
  "message": "",
  "data": [
    {
      "codTpd": 24,
      "desTpd": "AJUDA DE CUSTO ALIMENTACAO"
    },
    {
      "codTpd": 23,
      "desTpd": "ALUGUEL"
    },
    {
      "codTpd": 1,
      "desTpd": "BOLETO"
    },
    {
      "codTpd": 16,
      "desTpd": "CONSORCIO"
    },
    {
      "codTpd": 9,
      "desTpd": "CUPOM FISCAL"
    },
    {
      "codTpd": 15,
      "desTpd": "DEBITO AUTOMATICO"
    },
    {
      "codTpd": 19,
      "desTpd": "DIVERSOS"
    },
    {
      "codTpd": 14,
      "desTpd": "DIVERSOS 3° KF"
    },
    {
      "codTpd": 13,
      "desTpd": "ESPECIAIS"
    },
    {
      "codTpd": 6,
      "desTpd": "FATURA DE LOCACAO"
    },
    {
      "codTpd": 5,
      "desTpd": "FATURA DE SERVICO"
    },
    {
      "codTpd": 20,
      "desTpd": "FOLHA DE PAGAMENTO"
    },
    {
      "codTpd": 10,
      "desTpd": "IPVA"
    },
    {
      "codTpd": 25,
      "desTpd": "LOCACAO"
    },
    {
      "codTpd": 2,
      "desTpd": "NOTA FISCAL DE PRODUTO"
    },
    {
      "codTpd": 3,
      "desTpd": "NOTA FISCAL DE SERVICO"
    },
    {
      "codTpd": 17,
      "desTpd": "OS"
    },
    {
      "codTpd": 22,
      "desTpd": "PAGAMENTO ESPECIAL"
    },
    {
      "codTpd": 7,
      "desTpd": "PARTE DIARIA"
    },
    {
      "codTpd": 21,
      "desTpd": "PRESTADOR DE SERVIÇOS TERCEIRIZADO"
    },
    {
      "codTpd": 4,
      "desTpd": "RECIBO"
    },
    {
      "codTpd": 18,
      "desTpd": "REEMBOLSO"
    },
    {
      "codTpd": 12,
      "desTpd": "SALARIO"
    },
    {
      "codTpd": 11,
      "desTpd": "TARIFAS BANCARIAS"
    },
    {
      "codTpd": 26,
      "desTpd": "TROCA / VENDA DE VEICULOS"
    }
  ]
}`

preciso pegar o json que esta no "data"
existe alguma propriedades?

**Comment by viniciussanchez** [comment]
Bom dia...
A principio não. Você teria que pegar ele de forma manual para passar para o DataSet-Serialize

**Comment by viniciussanchez** [comment]
Implementado: 54aeba4adb7bd23358ad712cfa887944b4725f4c
Versão: [Release v2.5.2](https://github.com/viniciussanchez/dataset-serialize/releases/tag/v2.5.2)
