### ISSUE TITLE
Violação de acesso de memória (FPC: 3.3 - Lazarus: 3) 

### ISSUE THREAD

**Issue by edsontmarques** [viniciussanchez/dataset-serialize#211]
Detectei um erro de violação de acesso de memória ao dar Free em um TJSONObject na seguinte situação:

```
procedure TfraUsuarios.DoRequestJSON;
var
  Response: IResponse;
  JSONObject: TJSONObject;
begin
  Response := TRequest.New
                                         .BaseURL('http://xxx:9000/yyy/zzz');
                                         .ContentType('application/json')
                                         .Get;

  JSONObject := GetJSON(Response.Content) as TJSONObject;
  try
    if JSONObject.Booleans['status'] then
    begin
      dtsTeste.DataSet.DisableControls;
      try
        dtsTeste.DataSet.Close;
        dtsTeste.DataSet.LoadStructure(JSONObject.Arrays['structure']);
        dstTeste.CreateDataset;
        dtsTeste.DataSet.LoadFromJSON(JSONObject.Arrays['data']);
        dtsTeste.DataSet.First;
      finally
        dtsTeste.DataSet.EnableControls;
      end;
  finally
    JSONObject.Free;
  end;
end; 
```                   

Tanto LoadStructure() como LoadFromJSON() podem provocar a violação de acesso. Basta comentar qualquer uma das duas que o JSONObject.Free funciona normalmente.

Infelizmente não tive condições de aprofundar mais para entender a causa.

**Comment by mbertolani** [comment]
Verifica a função GetJson, no seu exemplo o compilador vai liberar a o JSONObject automaticamente, por isso dá erro quando tenta destruir o objeto

**Comment by viniciussanchez** [comment]
Se olhar o código fonte dos métodos, ou até mesmo no Ctrl+barra de espaço, vai ver a documentação feita em XML Doc

![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/bde3ee33-4085-4997-9a37-a58287a304c8)

Existe o parâmetro para você informar quem é o dono do JSON. No caso por padrão o dono é o DataSet-Serialize. Ou seja, ele mesmo destroi o JSON passado como parâmetro. Sendo assim, quando você tenta destruir o JSON depois, vai dar o Access violation, porque ele já foi destruído.

O mesmo acontece no LoadFromJSON:

![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/dd3c8448-3491-4567-81ea-65ac7d41271f)

Desculpa a demora em responder...
