### ISSUE TITLE
LoadFromJson com chave que possue "underline"

### ISSUE THREAD

**Issue by bitencourtrafael** [viniciussanchez/dataset-serialize#212]
Durante alguns testes precisei consumir uma api que me retornou as chaves do json com underline como separador, porém ao tentar importar com o LoadFromJson o campo não preenche na query fica vazio, já aconteceu algum caso assim?

Ex: qrySamples.LoadFromJSON('{"access_token":"XXXXyyyyAAAaaaa"}');

**Comment by viniciussanchez** [comment]
Bom dia.. isso é configuração.
![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/cdf6196b-7eb6-4cdb-a79c-4e89de5eb101)
Só alterar para o formato que você quer trabalhar...

**Comment by bitencourtrafael** [comment]
Olá Vinicius, funcionou perfeitamente o que você me indicou, porém me deparei com outra situação, quando tenho uma chave e nela temos um array, nesse caso também esta ficando em branco, dei uma olhada na documentação para ver se poderia ser alguma outra configuração mas não obtive sucesso.

Ex:
```pascal
qrySamples.LoadFromJSON('{"items": [{"id": "id1"},{"id": "id1"}]}')
```

**Comment by viniciussanchez** [comment]
Da uma olhada na pasta samples. Cada nível do array corresponde a um dataset. Ou seja teria que fazer um mestre detalhe de datasets para conseguir carregar algo desse tipo. 
```
[
  {
    "pedido": 1,
    "valor": 10,
    "itens": [
      {
        "codigo": 1,
        "descricao": "teste"
      },
      {
        "codigo": 2,
        "descricao": "teste 2"
      }
    ]
  },
  {
    "pedido": 2,
    "valor": 10,
    "itens": [
      {
        "codigo": 1,
        "descricao": "teste"
      },
      {
        "codigo": 2,
        "descricao": "teste 2"
      }
    ]
  }
]
```

esse json de cima mesmo, tem 2 querys, uma para carregar o primeiro nivel que é o pedido, e outra para carregar o segundo que é os itens.
