### ISSUE TITLE
Erro Floating poinr

### ISSUE THREAD

**Issue by Jetavela** [viniciussanchez/dataset-serialize#218]
Bom dia, alguma dica para resolver esse problema? 

![WhatsApp Image 2023-12-12 at 11 25 10 AM](https://github.com/viniciussanchez/dataset-serialize/assets/153627528/58f339c5-3f01-4d94-b856-d3d40117407c)

**Comment by viniciussanchez** [comment]
Como você está fazendo? Qual o processo? Tem algum projeto / json para simular?
