### ISSUE TITLE
Cannot find type for field "MEU_CAMPO". - Erro ao usar .ToJSONObject() em um dataset que tenha campo char(16) octets

### ISSUE THREAD

**Issue by RicardoCassio** [viniciussanchez/dataset-serialize#219]
Ao tentar passar um dataset que tenha campo char(16) octets para json usando a função .ToJSONObject(), recebo o seguinte erro:

Cannot find type for field "MEU_CAMPO"

Existe alguma configuração ou alternativa para contornar isso?

**Comment by viniciussanchez** [comment]
Boa tarde...
se olhar o código vai ver que tratamos a maioria dos tipos de dados já

![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/3c2f23ca-87d3-4d1a-8ba4-c28cc26b9766)

Esse seu campo, deve estar com algum tipo que nao tratamos ainda... precisava identificar qual é, e fazer os devidos tratamentos... Se quiser pode enviar um pull request que aceitamos...

**Comment by viniciussanchez** [comment]
vlw

**Comment by viniciussanchez** [comment]
Bom dia... conseguiu identificar o seu Field Type?

**Comment by maiconsaraiva** [comment]
Fala @viniciussanchez , tudo bem? O Cássio trabalha junto comigo e está de férias. Eu fiz o PR impelementando o formato ausente, que é o tipo ftBytes.
Segue o PR:
https://github.com/viniciussanchez/dataset-serialize/pull/223
