### ISSUE TITLE
armazenar o ID_USUARIO obtido no processo de autenticação com o HorseBasicAuthentication.

### ISSUE THREAD

**Issue by roger-e-get** [viniciussanchez/dataset-serialize#227]
Boa tarde Vinícius!
Na API que estou trabalhando é utilizado o HorseBasicAuthentication para validar usuário e senha.
No momento da autenticação eu gostaria de armazenar o ID do usuário para usar posteriormente nos processos seguintes. Minha dificuldade é saber onde guardar esta informação. Pensei em adicioná-la na própria requisição onde recebo o usuário e senha, mas no HorseBasicAuthentication me parece que a requisição não está disponível/visível.
Você poderia me dar uma dica de como proceder para armazenar esta informação buscada durante a autenticação do usuário?

**Comment by viniciussanchez** [comment]
Boa tarde... de fato esse middleware nao tem nada nesse sentido... você poderia criar seu próprio middleware que faça isso pra você, ou, sempre que precisar, pegar o Req.Headers obter o basic e chegar até o usuário novamente... uma outra possibilidade tambem seria add o ID do usuário no Response. O middleware tem um callback diferente que da acesso ao response.. poderia mudar o seu callback e passar essa informação lá

**Comment by viniciussanchez** [comment]
![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/171f9649-677f-4966-ab96-909fdff7d939)
Esses aqui

**Comment by viniciussanchez** [comment]
![image](https://github.com/viniciussanchez/dataset-serialize/assets/16382981/856d7a38-deda-4cd5-b2f2-58edac86f115)

**Comment by roger-e-get** [comment]
show! Muito obrigado Vinícius, pelo auxílio. Foi de grande ajuda!!!
