### ISSUE TITLE
[DÚVIDA] - Dataset Serialize + ZeosLib

### ISSUE THREAD

**Issue by LukeChagastec** [viniciussanchez/dataset-serialize#228]
Boa tarde.

É apenas uma dúvida, mas este componente funciona com a ZeosLib?

Eu vi que os componentes do Zeos não descendem dos mesmos objetos do SqlSb (lazarus) e Firedac (delphi).

Obrigado.

**Comment by viniciussanchez** [comment]
Funciona com todos os componentes que herde de TDataSet...

**Comment by LukeChagastec** [comment]
Entendi, obrigado!
