### ISSUE TITLE
"error": "Invalid variant type cast"  somente no Lazarus

### ISSUE THREAD

**Issue by FernandoMassa** [viniciussanchez/dataset-serialize#231]
"error": "Invalid variant type cast" No Lazarus, o que não ocorre no Delphi.

Estou fazendo o curso ministrado por ti Vinicius (Fullstack Delphi / Lazarus & Angular Backend em Lazarus) e na aula 7 do Lazarus as coisas não davam certo. (Fiz a de Delphi e foi tudo suave) 
Depois de várias tentativas, baixei o exemplo que vc mesmo fez e vi que funcionava e umas das coisas diferentes eram as versões dos middlewares daí quando troquei pela versão antiga, funcionou.

Imagino que vc tenha esses arquivos e poderá constatar que de fato no Lazarus deixa de funcionar. Tomara que se seja simples de resolver.

Obrigado pelo seu trabalho e pela ajuda que vc brinda a toda a comunidade de desenvolvedores!! 
Abraço!

**Comment by viniciussanchez** [comment]
Bom dia... você chegou a identificar onde necessariamente estaria o problema? E se o problema está em middlewares como você falou, talvez o correto seria a gente discutir sobre isso no middleware em questão.

> Obrigado pelo seu trabalho e pela ajuda que vc brinda a toda a comunidade de desenvolvedores!!
Abraço!

Vlww

**Comment by FernandoMassa** [comment]
Boa tarde Vinicius, aqui no anexo está o teu material com o middleware do DataSet.Serialize novo.

[curso-lazarus-angular.zip](https://github.com/viniciussanchez/dataset-serialize/files/14604717/curso-lazarus-angular.zip)

Note que o erro ocorre exatamente ao passar na linha 54.
![image](https://github.com/viniciussanchez/dataset-serialize/assets/579358/7863b07e-a802-4701-8a1e-332871b78146)

Acredito que esse "LoadFromJSON" tenha alguma questão com a informação que recebe quando compilada no lazarus, pois como falei, pelo Delphi foi de boa.

Espero ter ajudado, não me animei a debugar o DataSet.Serialize, certamente está além da minha capacidade atual.

**Comment by viniciussanchez** [comment]
Acho que o erro pode ter relação com essa issue aqui:
https://github.com/viniciussanchez/dataset-serialize/issues/224

Eu já até fiz o ajuste. Poderia baixar a versão "Release v2.5.7" e testar? É a última disponível

**Comment by FernandoMassa** [comment]
Efetivamente deu certo. Resolvido o problema na nova release v2.5.7
