### ISSUE TITLE
Duvida sobre Json Array no objeto

### ISSUE THREAD

**Issue by FelipeAngelini** [viniciussanchez/dataset-serialize#24]
Suponhamos que tenho o JSON abaixo, como seria a serialização/deserialização para um dataset? 

`{
    "id": 1,
    "descricao": "teste",
    "filhos": [
        1, 2, 3, 4]
}
`

Teria um memTable com os fields:
id: TIntegerField
descricao: TStringField
filhos: ??????

Ele não seria um DataSetField pois não é um objeto, eu tenho somente uma lista de inteiros.

Alguma sugestão de como utilizar?

Grato.

**Comment by viniciussanchez** [comment]
Boa tarde,
Acredito que pelo seu exemplo, não vai ser possível utilizar o dataset-serialize hoje, mas a noite vou dar uma olhada e qualquer coisa já ajusto o que for necessário.
Uma solução, seria sim usar o DataSetField, porem na sua query filha teria um campo, onde seria inserido os valores 1,2,3,4.

**Comment by viniciussanchez** [comment]
Implementado:

![image](https://user-images.githubusercontent.com/16382981/64394098-f474a600-d02a-11e9-8cab-671898624150.png)
