### ISSUE TITLE
Dúvida sobre nome dos fields

### ISSUE THREAD

**Issue by jcaique** [viniciussanchez/dataset-serialize#246]
Como posso deixar o nome dos fields iguais aos que eu tenho no dataset? 
Exemplo: Todos os campos da tabela estão como 'dt_Campo1', 'cd_Campo2', há a possibilidade de deixar exatamente desta forma?

Atualmente ao exportar para json, os campos vêm "cdCampo2", 'dtCampo1'.

**Comment by viniciussanchez** [comment]
![image](https://github.com/user-attachments/assets/d831cd99-d81d-4aa0-b35f-d2503ea13748)
