### ISSUE TITLE
Duvidas - LowerCamelCase - JsonArray master-detail

### ISSUE THREAD

**Issue by ElvisHotz** [viniciussanchez/dataset-serialize#48]
Ola.
Primeiramente parabens a todos os envolvidos pelo trabalho. exelente ferramenta!

Estou gerando um JSONArray master - detail - detail que seriam grupo->subgrupos->adicionais
a primeria questao e que cuando marco o LowerCamelCase:= true, o detail fica por exemplo dessa forma ->"sUBGRUPOS", "aDICIONAIS"

outra questao e quando por exemplo nao existem adicionais na detail teria uma forma de gerar 
ela vazia?.  exemplo -> "Adicionais": [] ;

os campos currency por exemplo "valor": "0,00" estao vindo como string no json, tem alguma forma de colocar eles como double?

no mastes estou fazendo da seguinte forma
  LJSONArray  := GRUPOS.ToJSONArray(False,True);

Obrigado.

segue uma amostra do json gerado. 

{
        "idGrupo": 9,
        "descricao": "ESFIHAS",
        "sUBGRUPOS": [
            {
                "id": 11,
                "idSubgrupo": 11,
                "descricao": "ESFIHAS",
                "imagem": "",
                "agrupa": "N",
                "nAgrupa": null,
                "idGrupo": 9,
                "nFatias": 0,
                "valor": "0,00"
            }
        ]
    },
    {
        "idGrupo": 6,
        "descricao": "LANCHES",
        "sUBGRUPOS": [
            {
                "id": 8,
                "idSubgrupo": 8,
                "descricao": "LANCHES",
                "imagem": "",
                "agrupa": "N",
                "nAgrupa": null,
                "idGrupo": 6,
                "nFatias": 0,
                "valor": "0,00",
                "aDICIONAIS": [
                    {
                        "id": 18,
                        "descricao": "ADICIONAIS",
                        "valor": "2,00",
                        "idSubgrupo": 8
                    },
                    {
                        "id": 5,
                        "descricao": "EGG",
                        "valor": "1,50",
                        "idSubgrupo": 8
                    }
                ]
            }
        ]
    },

**Comment by viniciussanchez** [comment]
> a primeria questao e que cuando marco o LowerCamelCase:= true, o detail fica por exemplo dessa forma ->"sUBGRUPOS", "aDICIONAIS"

R: como está o nome dos seus DataSet?

> outra questao e quando por exemplo nao existem adicionais na detail teria uma forma de gerar
ela vazia?. exemplo -> "Adicionais": [] ;

R: Teria que criar uma configuração pra isso, ai daria pra fazer sim

> os campos currency por exemplo "valor": "0,00" estao vindo como string no json, tem alguma forma de colocar eles como double?

R: Atualmente tem um parâmetro pra você formatar os valores currency da forma que você deseja, mas por causa disso ele exporta como string. Daria pra tratar isso também e ajustar para exportar como currency sim

![image](https://user-images.githubusercontent.com/16382981/83903710-fe9c1000-a734-11ea-8ef2-41b89e6adbe4.png)

**Comment by ElvisHotz** [comment]
Obrigado pela rapida resposta. 
Os dataset estao nomeados assim->  (GRUPOS,SUBGRUPOS,ADICIONAIS);

**Comment by viniciussanchez** [comment]
Você quer colaborar com o projeto e criar essas configurações? Assim entraria na lista dos colaboradores também...

**Comment by mateusvicente100** [comment]
Boa tarde. Achei interessante essa questão do currency. Não tinha me atendado que estava exportando como string. Seria bacana ter uma opção para exportar como TJSONNumber.
Em relação as duas outras questões, a primeira pode ser por causa do nome dos datasets (podemos ver como tratar) e a segunda teria como implementar sim.

**Comment by ElvisHotz** [comment]
> Você quer colaborar com o projeto e criar essas configurações? Assim entraria na lista dos colaboradores também...

Sim com certeza, posso colaborar com o projeto.

**Comment by viniciussanchez** [comment]
Certo então, aguardamos seu Pull Request com as implementações. 
Se tiver alguma dúvida pode comentar aqui que vamos respondendo ok

**Comment by ElvisHotz** [comment]
blz combinado

**Comment by viniciussanchez** [comment]
Criei uma configuração para exportar os dataset quando tiverem vazios... vai resolver o seu problema:

> outra questao e quando por exemplo nao existem adicionais na detail teria uma forma de gerar
ela vazia?. exemplo -> "Adicionais": [] ;

TDataSetSerializeConfig.GetInstance.Export.ExportEmptyDataSet

**Comment by viniciussanchez** [comment]
> os campos currency por exemplo "valor": "0,00" estao vindo como string no json, tem alguma forma de colocar eles como double?

Se deixar o parâmetro TDataSetSerializeConfig.GetInstance.Export.FormatCurrency em branco vai exportar como JSONNumber, se passar alguma informação ele vai exportar como JSONString e vai formatar o valor em questão

**Comment by viniciussanchez** [comment]
Está faltando verificar apenas o problema referente ao nome dos DataSet:

> a primeria questao e que cuando marco o LowerCamelCase:= true, o detail fica por exemplo dessa forma ->"sUBGRUPOS", "aDICIONAIS"

**Comment by ElvisHotz** [comment]
Ows. ok . eu iria olhar este final de semana. mas como vc ja fez obrigado! ainda nao baixei a versao nova. estou em outros projetos. mas assim que puder dou uma olhada. mais uma vez Obrigado!

**Comment by viniciussanchez** [comment]
;)
