### ISSUE TITLE
Error during load structure with string field size 0

### ISSUE THREAD

**Issue by ricardodarocha** [viniciussanchez/dataset-serialize#49]
Save structure on Dataset1 produces certain string fields with size = 0 (not always, just some)
When I restore the Structure on Dataset2 occur the error 
     **"Size not defined for field <INSC_MUNICIPAL>."**

pt-br
Ao salvar a estrutura do Dataset1 algums campos String ficam com tamanho 0
Quando eu restauro esta mesma estrutura no Dataset2 ocorre o erro "Tamanho não definido para o campo <INSC_MUNICIPAL>"

`[{"alignment":"taLeftJustify","fieldName":"INSC_ESTADUAL","displayLabel":"INSC_ESTADUAL","dataType":"ftString","size":15,"key":false,"origin":"INSCRICAOCLIENTE","required":false,"visible":true,"readOnly":false,"autoGenerateValue":"arNone"},{"alignment":"taLeftJustify","fieldName":"INSC_MUNICIPAL","displayLabel":"INSC_MUNICIPAL","dataType":"ftString","size":0,"key":false,"origin":"INSC_MUNICIPAL","required":false,"visible":true,"readOnly":true,"autoGenerateValue":"arDefault"},{"alignment":"taLeftJustify","fieldName":"SUFRAMA","displayLabel":"SUFRAMA","dataType":"ftString","size":0,"key":false,"origin":"SUFRAMA","required":false,"visible":true,"readOnly":true,"autoGenerateValue":"arDefault"},{"alignment":"taLeftJustify","fieldName":"TELEFONE","displayLabel":"TELEFONE","dataType":"ftString","size":15,"key":false,"origin":"TELEFONECLIENTE","required":false,"visible":true,"readOnly":false,"autoGenerateValue":"arNone"}]`

**Comment by viniciussanchez** [comment]
Understand...
Thus, there is no way for FireDAC to know the size of the field. So it is 0.
Can't use calculated fields? Or else manually set the size of these fields?

Entendi...
Dessa forma, realmente não tem como o FireDAC saber o tamanho do campo. Por isso fica 0.
Não da pra usar campos calculados? Ou então definir manualmente o tamanho desses campos?

**Comment by ricardodarocha** [comment]
I've solved this for a while returning ' ' one character length string instead of '' empty string.
I suggest you change the structure array to return a size of 255 for field string length 0, to prevent future problems. I vote to close the issue.

Eu solucionei isto por enquanto retornarndo uma string de um caractere em vez de string vazia.
Eu sugiro a você mudar a estrutura para retornar o tamanho de 255 para estes campos string de tamanho 0, para prevenir que outros colegas sofram do mesmo mal.
De qualquer forma, acredito que podemos encerrar a discussão e dar o problema como solucionado.
Grato pelo seu tempo.
