### ISSUE TITLE
Argument `AOnlyUpdatedRecords` does not export only changes in the DataSet

### ISSUE THREAD

**Issue by dev-mustache** [viniciussanchez/dataset-serialize#57]
I tried to fetch data into a dataset using `TFDQuery` without any modification to the data, the `ToJSONArray(true)` exported the entire dataset but I expected `ToJSONArray(true)` to export an empty array because the dataset is clean.

Please guide me what went wrong, thanks.

```pas
procedure ExportChanges;
var
  arr: TJSONArray;
begin
  with qMaster do begin
    CachedUpdates := True;
    Open('SELECT first_name, last_name, email FROM customers');
    CommitUpdates;

    arr := ToJSONArray(true);
    try
      mmoJSON.Lines.Add(arr.Format);
    finally
      arr.Free;
    end;
  end;
end;
```

**Comment by viniciussanchez** [comment]
For the 'AOnlyUpdatedRecords' argument to work, you must work with the 'CacheUpdate' = true

**Comment by dev-mustache** [comment]
> For the 'AOnlyUpdatedRecords' argument to work, you must work with the 'CacheUpdate' = true

according to my sourcecode, I did `CachedUpdates := true;` but don't know why I still get the entire records from the dataset.

**Comment by viniciussanchez** [comment]
If you load your dataset, with the property 'CacheUpdates' = True, all records will be understood as new records. The correct thing is that you load the dataset with the data and then activate the 'CacheUpdate' property to control the actions.

**Comment by dev-mustache** [comment]
> If you load your dataset, with the property 'CacheUpdates' = True, all records will be understood as new records. The correct thing is that you load the dataset with the data and then activate the 'CacheUpdate' property to control the actions.

I had tried with the coding below but I still couldn't get it to work, could you please show me in code how can I sequence the statements to get it works?, thanks.

```pas
procedure ExportChanges;
var
  arr: TJSONArray;
begin
  with qMaster do begin
    Close;
    CachedUpdates := false; // make sure it's false before opening the dataset
    Open('SELECT first_name, last_name, email FROM customers');
    CachedUpdates := true; // set it true after opening the dataset
    arr := ToJSONArray(true);
    try
      Memo1.Lines.Add(arr.Format);
    finally
      arr.Free;
    end;
  end;
end;
```
