### ISSUE TITLE
How can I get the inserted, edited and deleted records of a dataset that is not a child dataset?

### ISSUE THREAD

**Issue by jmjasa** [viniciussanchez/dataset-serialize#61]
Hi,

I want to  get only the inserted, edited and deleted records of the dataset (with CachedUpdates = True).
The dataset does not have child datasets.

I am using a FDMemTable to get the changed records: inserted, edited and deleted, of the dataset with the following instructions:
var
  booChildRecords,
  booOnlyUpdatedRecords : Boolean;
  jsonChangeViews : TJSONValue;
  
begin
  { parMTChangeViews : TFDMemTable that receives the FDMemTable (with CachedUpdates = True), that contains 
    all the records inserted, updated and deleted.
   It is not a child dataset.}

   booChildRecords  := False;
   booOnlyUpdatedRecords := True;
   jsonChangeViews := parMTChangeViews.ToJSONArray(booOnlyUpdatedRecords, booChildRecords);
 
end;

The above-instruction only gets the inserted, edited and deleted records of a child dataset? 
How can I get the changed records of a dataset that is not a child dataset?

**Comment by viniciussanchez** [comment]
> The above-instruction only gets the inserted, edited and deleted records of a child dataset?

R: Yes

> The above-instruction only gets the inserted, edited and deleted records of a child dataset?

R: You can modify FilterChanges property of TFDMemTamble, before to call .ToJSONArray()

![image](https://user-images.githubusercontent.com/16382981/91999149-723cc180-ed12-11ea-9e63-f49100e2379f.png)

**Comment by rickdroio** [comment]
Dears, do you have any solution for FPC Lazarus? I've checked at DataSet.Serialize.Export source has a IF DEFINED to ignore "OnlyUpdatedRecords" param.
Thanks
