### ISSUE TITLE
DataSet.Serialize no Lazarus

### ISSUE THREAD

**Issue by Flexnetsistemas** [viniciussanchez/dataset-serialize#71]
Instalei com Boss em um projeto lazarus porém não reconhece a unit na uses

```
uses
  {$IFDEF UNIX}{$IFDEF UseCThreads}
  cthreads,
  {$ENDIF}{$ENDIF}
  Horse, Horse.Jhonson, fpjson, SysUtils, UDM, DataSet.Serialize; 
```

..
foi criado a pasta /modules no projeto com as middlewares baixadas, mas não encontra no projeto

preciso fazer mais alguma configuração no projeto ou no lazarus ?

**Comment by viniciussanchez** [comment]
O Boss ainda não é compatível com o Lazarus. Apenas com o Delphi. A versão nova do Boss vai ser compatível.
