### ISSUE TITLE
Campos do Tipo ftMemo

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/dataset-serialize#80]
Boa tarde,
Tenho um campo no meu memtable que e do tipo ftMemo, quanto uso todos os componentes REST do delphi ele popula esse tampo agora quando uso o dataset-serialize este campo não e populado... tem algo especifico que tenho que fazer?

**Comment by viniciussanchez** [comment]
Boa tarde,

![image](https://user-images.githubusercontent.com/16382981/103935545-80a64a00-5105-11eb-8c08-04d8565dda49.png)

Como mostra a imagem acima, era para ele estar importando normalmente.
Tem como passar mais detalhes? Você costuma adicionar o Field no memtable? Ou deixa ele ser criado sozinho?

**Comment by alissonrodrigo** [comment]
Primeiramente obrigado por responder!Então estou adicionando manualmente, tentei deixar em branco mais simplesmente trava aplicação quando e criado automaticamente 
    Em quinta-feira, 7 de janeiro de 2021 16:30:39 BRT, Vinicius Sanchez <notifications@github.com> escreveu:  
 
 


Boa tarde,



Como mostra a imagem acima, era para ele estar importando normalmente.
Tem como passar mais detalhes? Você costuma adicionar o Field no memtable? Ou deixa ele ser criado sozinho?

**Comment by viniciussanchez** [comment]
Estranho, aqui também tenho fields ftMemo e não tenho problema. Talvez vai ter que me mostrar ou adicionar algum projeto de exemplo com essa situação para que possamos avaliar. Ou então você mesmo debugar o projeto, e ajustar o erro que esta tendo e depois enviar o seu pull request para que possamos ajustar.

**Comment by alissonrodrigo** [comment]
O cenario e simples tenho uma api que faço uma requisição atravez do RESTRequest4Delphi e popula o memtable
  if Funcoes.ConectadoInternet = True then  begin    Resposta := TRequest.New.BaseURL(sURI).Accept(TURIs.Accept).DataSetAdapter(memNoticias).Get;    if Resposta.StatusCode = 200 then    begin      SalvarNoticiasLocal;      Result := True;    end    else      Result := false;  end  else    Result := False;

Meu Json
[  {    "idartigo": "3",    "titulo": "aaaa",    "data_publicacao": "05\/01\/2021",    "hora_publicacao": "10:14",    "idautor": null,    "idsecretaria": null,    "secretaria": null,    "conteudo": "asdasd asd asd",    "imagem1": "imagens\/artigos\/3\/1186942097.jpg",    "imagem2": "imagens\/artigos\/3\/1383520251.jpg",    "imagem3": "imagens\/artigos\/3\/967325527.jpg",    "total_atualizacoes": "1",    "curtidas": "0",    "visualizacoes": "0"  }]
    Em quinta-feira, 7 de janeiro de 2021 16:45:47 BRT, Vinicius Sanchez <notifications@github.com> escreveu:  
 
 


Estranho, aqui também tenho fields ftMemo e não tenho problema. Talvez vai ter que me mostrar ou adicionar algum projeto de exemplo com essa situação para que possamos avaliar. Ou então você mesmo debugar o projeto, e ajustar o erro que esta tendo e depois enviar o seu pull request para que possamos ajustar.

**Comment by viniciussanchez** [comment]
O seu JSON ficaria assim então?

![image](https://user-images.githubusercontent.com/16382981/104008366-1d113080-5188-11eb-85bb-362eab74f321.png)

E desses campos ai qual que é o ftMemo?
