### ISSUE TITLE
Unicode characters appears incorrectly

### ISSUE THREAD

**Issue by chukkan** [viniciussanchez/dataset-serialize#81]
Unicode characters appears incorrectly. When a string contains Non-Latin characters, it leaves question marks (???).

**Comment by viniciussanchez** [comment]
Send me an example

**Comment by chukkan** [comment]
Vinicius, I have used for testing the 'basic" demo to test. Here is the screen-shot of the result I get.
![image](https://user-images.githubusercontent.com/49111946/105386499-8764af00-5c25-11eb-8629-a324ecf74306.png)

**Comment by viniciussanchez** [comment]
In the basic example, the country field type is TStringField. If you change field type to TWideString: 
![image](https://user-images.githubusercontent.com/16382981/105403165-262de300-5c07-11eb-8f5b-a4c960182498.png)
