### ISSUE TITLE
Samples\Lazarus\basic\basic.lpi can not compile, TArray<string> not availble yet in FPC?

### ISSUE THREAD

**Issue by PaulANormanNZ** [viniciussanchez/dataset-serialize#88]
Hi,

When I try to compile the project basic.lpi I get errors.

```
unit DataSet.Serialize.Samples.Basic;
(line 47)  FDataSetPrefix: TArray<string>;
```

From what I've seen on Lazarus Forums 

 ` TArray<string> may not yet be implemented in FPC?`

Is there a work around for Lazarus yet available please?

```
unit DataSet.Serialize.Samples.Basic;

Compile Project, Target: basic.exe: Exit code 1, Errors: 3
DataSet.Serialize.Config.pas(47,21) Error: Identifier not found "TArray"
DataSet.Serialize.Config.pas(47,27) Error: Error in type definition
DataSet.Serialize.Config.pas(47,27) Fatal: Syntax error, ";" expected but "<" found
```
Lazarus 2.0.8 r62944 FPC 3.0.4 x86_64-win64-win32/win64

Kind regards,
Paul

**Comment by PaulANormanNZ** [comment]
For the sake completeness I installed the latest installation ..

`Lazarus 2.0.12 r64642 FPC 3.2.0 x86_64-win64-win32/win64`

And everything compiles very nicely thank you.
I do not know exactly which release of Lazarus/FPC introdices TArray<string> etc., 
but the above version does work.

Might be worth pitching that in the Read Me adding a section for Lazarus as well as Delphi?

Thnaks again for very fine work.

**Comment by viniciussanchez** [comment]
Hi ... thanks for reporting.
I only tested DataSet-Serialize using Lazarus in version 2.0.10
