### ISSUE TITLE
Format of floating point numbers.

### ISSUE THREAD

**Issue by JacoFourie** [viniciussanchez/dataset-serialize#92]
Hi. How do you format float or numbers. 
Where I select data from a table in postgresql the number fields will show like thi 1.3640000000000000E+003
But the number in the database is 1346

**Comment by viniciussanchez** [comment]
Hello, you tried it already?

```pascal
TDataSetSerializeConfig.GetInstance.Export.FormatCurrency := '0.00##';
```

**Comment by JacoFourie** [comment]
No this does not work. The format stays the same

**Comment by viniciussanchez** [comment]
This works yes.
Your field must be of type Currency
![image](https://user-images.githubusercontent.com/16382981/134160556-1d2dc793-277b-44d0-9df8-f2011de5dd88.png)

**Comment by JacoFourie** [comment]
So if the field is a double / flout in the DB how do I set the format ?

**Comment by viniciussanchez** [comment]
Today it is not possible. Would have to implement

**Comment by dbechelli** [comment]
> Hello, you tried it already?
> 
> ```pascal
> TDataSetSerializeConfig.GetInstance.Export.FormatCurrency := '0.00##';
> ```

Boa tarde, estou com a mesma dificuldade. Como devo proceder para esta configuração?

**Comment by dbechelli** [comment]
Estou utilizando Delphi 11:
![image](https://user-images.githubusercontent.com/98767236/151849854-25ee294c-cbd5-4fba-9356-f024cbf526e6.png)

**Comment by gilfgfilho** [comment]
Boa tarde.

Estou tendo esse problema também, usando delphi 11, quando uso um comando
 mtUsers.LoadFromJSON(memoArrayValue.Lines.Text);

Alguma sugestao?

**Comment by gilfgfilho** [comment]
Consegui resolver colocando

    TDataSetSerializeConfig.GetInstance.Import.DecimalSeparator := '.';

**Comment by marcospatzer** [comment]
> Consegui resolver colocando
> 
> ```
> TDataSetSerializeConfig.GetInstance.Import.DecimalSeparator := '.';
> ```

tive o mesmo problema, 
no 10.3 e 10.4 estava rodando, 
quando mudei pro 11 comecou apresentar o erro,
colocando o:

TDataSetSerializeConfig.GetInstance.Import.DecimalSeparator := '.';

resolveu o problema.
