### ISSUE TITLE
datetime field does not show time

### ISSUE THREAD

**Issue by ElvisHotz** [viniciussanchez/dataset-serialize#94]
I'm serializing this json and the datetime fields don't show the time.

{
  "id": "101178",
  "dataHoraInicial": "2021-06-01 07:01:47",
  "DataHoraFinal": "2021-06-01 07:31:11"
}

## config

  TDataSetSerializeConfig.GetInstance.DataSetPrefix                            := ['mt', 'qry'];
  TDataSetSerializeConfig.GetInstance.Export.FormatCurrency             := '0.00##';
  TDataSetSerializeConfig.GetInstance.Export.FormatDate                    := 'YYYY-MM-DD';
  TDataSetSerializeConfig.GetInstance.Export.FormatDateTime            := 'yyyy-mm-dd hh:mm:ss';
  TDataSetSerializeConfig.GetInstance.Export.ExportNullValues            := True;
  TDataSetSerializeConfig.GetInstance.Export.ExportEmptyDataSet      := True;
  TDataSetSerializeConfig.GetInstance.CaseNameDefinition                 := cndNone;
  TDataSetSerializeConfig.GetInstance.Export.ExportChildDataSetAsJsonObject := False;
  TDataSetSerializeConfig.GetInstance.DateInputIsUTC                         := True;

##prints

![print_data](https://user-images.githubusercontent.com/11537876/121547061-30982000-c9e2-11eb-926c-35b926bdedc7.png)
![print_fieldFDMemTable](https://user-images.githubusercontent.com/11537876/121547062-3130b680-c9e2-11eb-8a0c-c7fad67426a5.png)

**Comment by viniciussanchez** [comment]
Are you using the latest version available?

**Comment by ElvisHotz** [comment]
I installed it with boss install github.com/viniciussanchez/dataset-serialize
how to see the version?

**Comment by viniciussanchez** [comment]
See the boss.json file for the installed version.
The last version released is 2.3.1

**Comment by ElvisHotz** [comment]
ok the version is the same
![print_version](https://user-images.githubusercontent.com/11537876/121718300-8b03b000-cab8-11eb-842f-81c6fc22bc0c.png)

**Comment by viniciussanchez** [comment]
Understand.
Did you try to debug?

**Comment by viniciussanchez** [comment]
Examples
1994-11-05T08:15:30-05:00 corresponds to November 5, 1994, 8:15:30 am, US Eastern Standard Time.
1994-11-05T13:15:30Z corresponds to the same instant.

**Comment by ElvisHotz** [comment]
the datetime in json does not contain the letter T in the datetime

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/121729250-9d83e680-cac4-11eb-871e-5a8c1bdf9c0b.png)

**Comment by ElvisHotz** [comment]
OK, unfortunately I don't have server control that returns this, so I'm going to adapt some parser.
Thank you for everything.
