### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by JacoFourie** [viniciussanchez/dataset-serialize#97]
Hi.

The library seems to have a major memory leak.  

When I start the program this is the memory usage

![image](https://user-images.githubusercontent.com/17771641/124447687-e6f0ea00-dd81-11eb-9f54-58c2c8654da0.png)

After making a couple of calls to it where the library will convert the dataset into json the memory will grow a lot and not drop down again.

![image](https://user-images.githubusercontent.com/17771641/124447971-3800de00-dd82-11eb-90b0-9ed81314d4c0.png)

**Comment by JacoFourie** [comment]
OK it seems I have to free the TJSONArray after each use even if I did not create it. If I free it then the memory will not grow.

**Comment by viniciussanchez** [comment]
Yes, you need to free the JSON from memory after you use it.
