### ISSUE TITLE
ReportMemory

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/dataset-serialize#99]
Estou usando a biblioteca para converter um query para json como estou debugando o ReportMemoryLeaksOnShutdown esta ativo porem esta dando vazamento de memoria 

JSONObject, TJSONString, TJSONPair 

Posso está fazendo algo errado? Grato

**Comment by viniciussanchez** [comment]
Mostra o código...

**Comment by alissonrodrigo** [comment]
TTask.Run(
    procedure
    var
      jArray: TJSONArray;
    begin
      Codigo := CodigoUltimaColeta;
      Hoje := Now;

      qryOrdensColeta.Active := False;
      qryOrdensColeta.ParamByName('Hoje').AsDate := Hoje;
      qryOrdensColeta.ParamByName('Codigo').AsInteger := Codigo;
      qryOrdensColeta.Active := True;

      mtOrdensColeta.CloneCursor(qryOrdensColeta, True);

      jArray := mtOrdensColeta.ToJSONArray;
      EnviaColetas(jArray.ToJSON);

      jArray.Free;

    end).Start;

**Comment by viniciussanchez** [comment]
Pelo que eu vi você está destruindo o jArray. Não era pra dar memory leak. Deve ter alguma coisa errada ai, porque usamos muito aqui e não temos problema
